import NavigationBar from "@/components/navigation-bar/navigation-bar";
import "./globals.css";
import classes from "./layout.module.css";
import Footer from "@/components/footer/footer";
import ScaleOnFooterVisible from "@/components/UI-components/layout/ScaleOnFooterVisible";

import { AngebotProvider } from "./context/angebot-context";

export const metadata = {
  title: "VARM - Bequem & schnell zur Wärmedämmung!",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AngebotProvider>
          <section className={classes.wrapper}>
            <section className={classes.main} id="main">
              <NavigationBar />
              <section className={classes.content}>{children}</section>
            </section>
            <section className={classes.footerContent} id="footer">
              <Footer />
            </section>
          </section>

          {/* Now apply the ScaleOnFooterVisible component */}
          <ScaleOnFooterVisible
            contentSelector="#main" // Target the main section
            footerSelector="#footer" // Footer as the trigger
          />
          {/* Theme changer */}
        </AngebotProvider>
      </body>
    </html>
  );
}
